"""
TRAIN Framework - modules/vpn_config.py
WireGuard VPN configuration generator.

Registers: vpn-genkeys, vpn-config

Generates a WireGuard-compatible X25519 keypair (using the same curve and
encoding WireGuard itself uses) and writes ready-to-use server/client
.conf files. This does NOT bring up a network interface or require root -
it's a config generator, the same job `wg genkey`/`wg pubkey` plus manual
templating does. To actually activate a tunnel, install wireguard-tools
(`sudo apt install wireguard`) and run `wg-quick up <config>` yourself
after reviewing the generated files.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from core.tui_engine import Session, register_command

console = Console()

DEFAULT_VPN_PORT = 51820
DEFAULT_ALLOWED_IPS = "0.0.0.0/0, ::/0"


@dataclass
class WireGuardKeypair:
    private_key_b64: str
    public_key_b64: str


def generate_keypair() -> WireGuardKeypair:
    """
    Generates a WireGuard-compatible X25519 keypair. WireGuard keys are
    just raw 32-byte Curve25519 keys, base64-encoded - identical to what
    `wg genkey | tee private.key | wg pubkey > public.key` produces.
    """
    private_key = X25519PrivateKey.generate()
    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return WireGuardKeypair(
        private_key_b64=base64.b64encode(private_bytes).decode("ascii"),
        public_key_b64=base64.b64encode(public_bytes).decode("ascii"),
    )


@register_command("vpn-genkeys")
def cmd_vpn_genkeys(session: Session, args: list[str]) -> None:
    """Usage: vpn-genkeys   (generates a fresh WireGuard keypair, printed to the terminal)"""
    kp = generate_keypair()
    console.print(Panel(
        f"[bold]Private key:[/bold] {kp.private_key_b64}\n"
        f"[bold]Public key:[/bold]  {kp.public_key_b64}",
        title="WireGuard Keypair (X25519)", border_style="green",
    ))
    console.print("[yellow]Keep the private key secret - never share or commit it.[/yellow]")
    session.state["last_vpn_keypair"] = kp


def _build_server_conf(server_kp: WireGuardKeypair, client_kp: WireGuardKeypair,
                        server_ip: str, port: int, client_vpn_ip: str) -> str:
    return f"""# WireGuard server configuration
# Generated by TRAIN Framework - review before use, requires wireguard-tools installed.
[Interface]
PrivateKey = {server_kp.private_key_b64}
Address = {server_ip}
ListenPort = {port}
# SaveConfig = true
# Uncomment and adjust for NAT/forwarding if this server routes client traffic:
# PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Client
PublicKey = {client_kp.public_key_b64}
AllowedIPs = {client_vpn_ip}/32
"""


def _build_client_conf(client_kp: WireGuardKeypair, server_kp: WireGuardKeypair,
                        server_endpoint: str, port: int, client_vpn_ip: str,
                        allowed_ips: str) -> str:
    return f"""# WireGuard client configuration
# Generated by TRAIN Framework - review before use, requires wireguard-tools installed.
[Interface]
PrivateKey = {client_kp.private_key_b64}
Address = {client_vpn_ip}/32
# DNS = 1.1.1.1

[Peer]
PublicKey = {server_kp.public_key_b64}
Endpoint = {server_endpoint}:{port}
AllowedIPs = {allowed_ips}
PersistentKeepalive = 25
"""


@register_command("vpn-config")
def cmd_vpn_config(session: Session, args: list[str]) -> None:
    """
    Usage: vpn-config <server_endpoint> [server_vpn_ip] [client_vpn_ip] [port]
    Example:
      vpn-config vpn.example.com                     -> uses sensible defaults
      vpn-config 203.0.113.5 10.8.0.1 10.8.0.2 51820

    Generates a fresh keypair for both server and client, and writes two
    ready-to-review files: train_vpn_server.conf and train_vpn_client.conf.
    Neither is applied automatically - copy them to their respective
    machines and run `wg-quick up <file>` yourself after reviewing.
    """
    if not args:
        console.print("[red]Usage:[/red] vpn-config <server_endpoint> [server_vpn_ip] [client_vpn_ip] [port]")
        return

    server_endpoint = args[0]
    server_vpn_ip = args[1] if len(args) > 1 else "10.8.0.1/24"
    client_vpn_ip = args[2] if len(args) > 2 else "10.8.0.2"
    port = int(args[3]) if len(args) > 3 else DEFAULT_VPN_PORT

    console.print("[cyan]Generating WireGuard keypairs for server and client...[/cyan]")
    server_kp = generate_keypair()
    client_kp = generate_keypair()

    server_conf = _build_server_conf(server_kp, client_kp, server_vpn_ip, port, client_vpn_ip)
    client_conf = _build_client_conf(client_kp, server_kp, server_endpoint, port,
                                      client_vpn_ip, DEFAULT_ALLOWED_IPS)

    server_path = Path("train_vpn_server.conf")
    client_path = Path("train_vpn_client.conf")
    server_path.write_text(server_conf, encoding="utf-8")
    client_path.write_text(client_conf, encoding="utf-8")
    server_path.chmod(0o600)
    client_path.chmod(0o600)

    console.print(Panel(
        Syntax(server_conf, "ini", theme="ansi_dark"),
        title=f"Server config -> {server_path.resolve()}", border_style="green",
    ))
    console.print(Panel(
        Syntax(client_conf, "ini", theme="ansi_dark"),
        title=f"Client config -> {client_path.resolve()}", border_style="blue",
    ))
    console.print(
        "[yellow]Files written with 0600 permissions (owner-only). Copy each to its "
        "respective machine, install wireguard-tools, and run "
        "'sudo wg-quick up <file>' after reviewing.[/yellow]"
    )
    session.state["last_vpn_config"] = {"server": server_conf, "client": client_conf}
